version: '3.5'

services:
  dashboard:
    image: charypar/swarm-dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
    #   - 4040:8080
      - 8080
    environment:
      PORT: 8080
    deploy:
      labels:
        traefik.frontend.rule: Host:dashboard.${CLUSTER_DOMAIN}
        traefik.port: 8080
        traefik.docker.network: traefik-net
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - traefik-net

  portainer:
    image: portainer/portainer
    ports:
      - 5050:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        traefik.frontend.rule: Host:portainer.${CLUSTER_DOMAIN}
        traefik.port: 9000
        traefik.docker.network: traefik-net
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
