version: '3.5'

services:
  dashboard:
    image: charypar/swarm-dashboard:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # ports:
    #   - 4040:8080
    environment:
      PORT: 8080
    deploy:
      labels:
        traefik.frontend.rule: Host:dashboard.${CLUSTER_DOMAIN}
        traefik.port: 8080
        traefik.docker.network: traefik-net
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - traefik-net

  portainer:
    image: portainer/portainer:1.17.1
    # ports:
    #   - 5050:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        traefik.frontend.rule: Host:portainer.${CLUSTER_DOMAIN}
        traefik.port: 9000
        traefik.docker.network: traefik-net
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    networks:
      - traefik-net

  janitor:
    image: flaviostutz/docker-janitor:latest
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    environment:
      - SLEEP_TIME=86400
      - UNUSED_TIME=24h
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  traefik-net:
    external: true
